# Generated by Django 6.0.2 on 2026-02-24 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cierrecaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='idUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas', to='core.usuario', verbose_name='Usuario'),
        ),
    ]
