# Generated by Django 6.0.2 on 2026-02-24 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_mesa_idusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata')], default='efectivo', max_length=20, verbose_name='Método de Pago Principal'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata')], max_length=20, verbose_name='Método de Pago')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Pagado')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='core.usuario', verbose_name='Cajero')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='core.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
    ]
